### ISSUE TITLE
`CNNLFWExample.scala` throws `NoClassDefFoundError`

### ISSUE THREAD

**Issue by Sitin** [kogecoo/dl4j-examples-scala#5]
Running [CNNLFWExample.scala](../blob/master/src/main/scala/org/deeplearning4j/examples/convolution/CNNLFWExample.scala) throws

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageWriterSpiBase
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:210)
    at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
    at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
    at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
    at org.canova.image.recordreader.BaseImageRecordReader.<clinit>(BaseImageRecordReader.java:72)
    at org.deeplearning4j.examples.data.ImageDataPipelineExample$.main(ImageDataPipelineExample.scala:22)
    at org.deeplearning4j.examples.data.ImageDataPipelineExample.main(ImageDataPipelineExample.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: com.twelvemonkeys.imageio.spi.ImageWriterSpiBase
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 29 more
```

The simple code like

``` scala
val labeledPath = System.getProperty("user.home")+"/lfw"
val labels = for (f <- new File(labeledPath).listFiles().toList) yield f.getName
val recordReader = new ImageRecordReader(28, 28, true, new java.util.ArrayList(labels))
recordReader.initialize(new FileSplit(new File(labeledPath)))
```

does the same.

This reproduces older [issue](https://github.com/deeplearning4j/Canova/issues/44) with Java examples.

The java version of the code

``` java
String labeledPath = System.getProperty("user.home")+"/lfw";
List<String> labels = new ArrayList<>();
for(File f : new File(labeledPath).listFiles()) {
    labels.add(f.getName());
}
RecordReader recordReader = new ImageRecordReader(28, 28, true, labels);
recordReader.initialize(new FileSplit(new File(labeledPath)));
```

in Java examples works fine but fails at Scala project although they have the same dependencies.

**Comment by Sitin** [comment]
Can be fixed by

``` scala
"com.twelvemonkeys.imageio" % "imageio-core" % "3.1.1"
```

in `build.sbt`.

Looks like `DL4J` team should be informed about this issue...

**Comment by kogecoo** [comment]
Thank you for reporting the problem.
Currently CNNLFWExample seems to be removed from original [master](https://github.com/deeplearning4j/dl4j-0.4-examples) ([commit](https://github.com/deeplearning4j/dl4j-0.4-examples/commit/37a4b3f7bf772aecea79eb29a0c5635329810541)).
 dl4j-example-scala followed that modification, so the dependency of Canova is no longer required to build it.

 Again, I appreciate your helpful information. When the original master depends on Canova again, I'll reflect your feedback.
